[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
base64 = "0.21"
js-sys = "0.3"
wasm-bindgen = "0.2"
web-sys = { version = "0.3.63", features = ["Window", "Location", "Url", "Navigator", "Request", "console"] }
